### ISSUE TITLE
update LocalConfig to support multiple clusters based on the new design

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#1346]
```[tasklist]
### Tasks
- [ ] remove the `currentDeploymentName` from LocalConfig, it will now be a required parameter for all commands so we don't need it
- [ ] rename `clusterContextMapping` to `clusterRefs`
- [ ] what we previously called a `solo cluster` will now be a `cluster ref`, rename variables related to the LocalConfig as needed
```

Current Structure:
```yaml
userEmailAddress: john@doe.com
deployments:
  solo-deployment:
    namespace: solo-e2e
    clusters:
      - kind-solo-cluster
currentDeploymentName: solo-deployment
clusterContextMapping:
  kind-solo-cluster: kind-solo-cluster
```

Proposed New Structure:
```yaml
clusterRefs:
 cluster1: context1
 cluster2: context2
 cluster3: context3
deployments:
  deployment1:
    namespace: namespace1
    clusters:
      - cluster1
      - cluster2
  deployment2:
    namespace: namespace2
    clusters:
      - cluster1
      - cluster3
userEmailAddress: john@doe.com
```
