### ISSUE TITLE
bug: deployment add-cluster is skipping node numbers and network deploy is not using cluster-ref

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#1670]
in: https://github.com/hashgraph/solo/pull/1669

when I enable `it(`${testName}: network deploy`, async () => {` in `dual-cluster-full.test.ts`, I find that after `solo deployment add-cluster` that the remote config looks like this:
```
metadata:                                                                                                                                                                                                                           
  namespace: dual-cluster-full                                                                                                                                                                                                      
  deploymentName: dual-cluster-full-deployment                                                                                                                                                                                      
  state: pre-genesis                                                                                                                                                                                                                
  lastUpdatedAt: 2025-03-17T21:19:56.580Z                                                                                                                                                                                           
  lastUpdateBy: dual.full.cluster.test@host.com                                                                                                                                                                                     
  soloChartVersion: 0.45.0                                                                                                                                                                                                          
  hederaPlatformVersion: v0.59.4                                                                                                                                                                                                    
  hederaMirrorNodeChartVersion: ""                                                                                                                                                                                                  
  hederaExplorerChartVersion: ""                                                                                                                                                                                                    
  hederaJsonRpcRelayChartVersion: ""                                                                                                                                                                                                
  soloVersion: 0.35.1                                                                                                                                                                                                               
version: 1.0.0                                                                                                                                                                                                                      
clusters:                                                                                                                                                                                                                           
  e2e-cluster-alpha:                                                                                                                                                                                                                
    name: e2e-cluster-alpha                                                                                                                                                                                                         
    namespace: dual-cluster-full                                                                                                                                                                                                    
    deployment: dual-cluster-full-deployment                                                                                                                                                                                        
    dnsBaseDomain: cluster.local                                                                                                                                                                                                    
    dnsConsensusNodePattern: network-{nodeAlias}-svc.{namespace}.svc                                                                                                                                                                
  e2e-cluster-beta:                                                                                                                                                                                                                 
    name: e2e-cluster-beta                                                                                                                                                                                                          
    namespace: dual-cluster-full                                                                                                                                                                                                    
    deployment: dual-cluster-full-deployment                                                                                                                                                                                        
    dnsBaseDomain: cluster.local                                                                                                                                                                                                    
    dnsConsensusNodePattern: network-{nodeAlias}-svc.{namespace}.svc                                                                                                                                                                
components:                                                                                                                                                                                                                         
  relays: {}                                                                                                                                                                                                                        
  haProxies: {}                                                                                                                                                                                                                     
  mirrorNodes: {}                                                                                                                                                                                                                   
  envoyProxies: {}                                                                                                                                                                                                                  
  consensusNodes:                                                                                                                                                                                                                   
    node1:                                                                                                                                                                                                                          
      name: node1                                                                                                                                                                                                                   
      cluster: e2e-cluster-alpha                                                                                                                                                                                                    
      namespace: dual-cluster-full                                                                                                                                                                                                  
      state: non-deployed                                                                                                                                                                                                           
      nodeId: 0                                                                                                                                                                                                                     
    node3:                                                                                                                                                                                                                          
      name: node3                                                                                                                                                                                                                   
      cluster: e2e-cluster-beta                                                                                                                                                                                                     
      namespace: dual-cluster-full                                                                                                                                                                                                  
      state: non-deployed                                                                                                                                                                                                           
      nodeId: 2                                                                                                                                                                                                                     
  mirrorNodeExplorers: {}                                                                                                                                                                                                           
commandHistory:                                                                                                                                                                                                                     
  - deployment add-cluster                                                                                                                                                                                                          
  - deployment add-cluster                                                                                                                                                                                                          
  - "Executed by dual.full.cluster.test@host.com: network deploy --deployment                                                                                                                                                       
    dual-cluster-full-deployment --dev --quiet-mode --cache-dir                                                                                                                                                                     
    test/data/tmp/dual-cluster-full --namespace dual-cluster-full"                                                                                                                                                                  
lastExecutedCommand: "Executed by dual.full.cluster.test@host.com: network                                                                                                                                                          
  deploy --deployment dual-cluster-full-deployment --dev --quiet-mode                                                                                                                                                               
  --cache-dir test/data/tmp/dual-cluster-full --namespace dual-cluster-full"                                                                                                                                                        
flags:                                                                                                                                                                                                                              
  releaseTag: v0.59.4                                                                                                                                                                                                               
```
Notice it is skipping node1 with nodeId = 0.

Then, it seems to deploy node1 and node3 to both clusters instead of the correct node to each cluster.
