### ISSUE TITLE
Add GitHub runner telemetry to aid in diagnosing concurrent E2E test failures

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo#309]
## Possible Solutions
1. [workflow-telemetry-action](https://github.com/catchpoint/workflow-telemetry-action)
2. [Argo Prometheus Metrics](https://argo-workflows.readthedocs.io/en/latest/metrics/)
3. [Enabling GitHub ARC Metrics](https://www.kenmuse.com/blog/enabling-github-arc-metrics/)

## 1. workflow-temetry-action
It was discovered that there were two issues with this solution:
- No support for reusable workflows: https://github.com/catchpoint/workflow-telemetry-action/issues/67
- Self-hosted GH Runners require elevated security: https://github.com/catchpoint/workflow-telemetry-action/issues/44

## 2. Argo Prometheus Metrics
This might help us with some metrics such as the following:
- Keeping track of the duration of a workflow or template
- Keeping track of the number of times a Workflow or Template fails over time
- Custom metrics

## 3. Enabling GitHub ARC Metrics
Some metrics, however, no CPU or RAM utilization
- busy runners
- idle runners
- number of jobs assigned to a runner
- many more...

### NOTES:
- This hacky solution used a Datadog agent: https://www.cbui.dev/github-actions-self-hosted-runner-observability-and-monitoring/

**Comment by JeffreyDallas** [comment]
Experimented with `workflow-telemetry-action`
but getting this error

```
/runner/_work/_actions/catchpoint/workflow-telemetry-action/v1.8.4/dist/webpack:/workflow-telemetry-action/node_modules/@octokit/auth-action/dist-node/index.js:19
    throw new Error("[@octokit/auth-action] The token variable is specified more than once. Use either `with.token`, `with.GITHUB_TOKEN`, or `env.GITHUB_TOKEN`. See https://github.com/octokit/auth-action.js#createactionauth");
^
Error: [@octokit/auth-action] The token variable is specified more than once. Use either `with.token`, `with.GITHUB_TOKEN`, or `env.GITHUB_TOKEN`. See https://github.com/octokit/auth-action.js#createactionauth
```

Have tried different release versions, all get the same error

Workflow logs

https://github.com/hashgraph/solo/actions/runs/9164986979/job/25197553053

**Comment by jeromy-cannon** [comment]
@JeffreyDallas , looks like it is complaining about us having more than one token that it can use, we probably need to pick one and pass it in.  Here is the list of the ones we have (not including the default GITHUB_TOKEN):
![image](https://github.com/hashgraph/solo/assets/5412850/a4a9ae48-eaac-4fb0-b1f0-8c57f1831797)

so for your current code:
```
      - name: Workflow Telemetry ${{ inputs.custom-job-label || 'E2E Test' }}
        if: ${{ runner.os == 'linux' && inputs.npm-test-script == 'test-e2e-node-local-build' && !cancelled() && !failure() }}
        uses: catchpoint/workflow-telemetry-action@v1.8.4
        with:
          metric_frequency: 15
```
maybe try this if you haven't already:
```
      - name: Workflow Telemetry ${{ inputs.custom-job-label || 'E2E Test' }}
        if: ${{ runner.os == 'linux' && inputs.npm-test-script == 'test-e2e-node-local-build' && !cancelled() && !failure() }}
        uses: catchpoint/workflow-telemetry-action@v1.8.4
        with:
          metric_frequency: 15
          github_token: ${{ env.GITHUB_TOKEN }}
```
